theme: jekyll-theme-slate
title: Mustafa Can Coşkun's Progress Journal
description: This journal is established for IE 423 course within Boğaziçi University Industrial Engineering Department in Fall 2023 term. My assignments will be posted here.
